package com.microsoft.kapp.utils;

import com.facebook.AppEventsConstants;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
/* loaded from: classes.dex */
public final class StrappConstants {
    public static final int CUSTOM_STRAPP_CURRENT_LOCATION = 31;
    public static final int CUSTOM_STRAPP_LAST_UPDATED = 21;
    public static final int CUSTOM_STRAPP_PAGE_TITLE = 11;
    public static final int FINANCE_STRAPP_CHANGE = 13;
    public static final int FINANCE_STRAPP_DIVIDER = 12;
    public static final int FINANCE_STRAPP_GAIN_LAYOUT = 2;
    public static final int FINANCE_STRAPP_ICON = 21;
    public static final int FINANCE_STRAPP_LOSS_LAYOUT = 1;
    public static final int FINANCE_STRAPP_SYMBOL = 11;
    public static final int FINANCE_STRAPP_VALUE = 22;
    public static final String NOTIFICATION_SERVICE_AQUAMAIL = "org.kman.AquaMail";
    public static final String NOTIFICATION_SERVICE_ASUS_EMAIL = "com.asus.email";
    public static final String NOTIFICATION_SERVICE_BLUE_MAIL = "com.trtf.blue";
    public static final String NOTIFICATION_SERVICE_BOOMERANG = "com.baydin.boomerang";
    public static final String NOTIFICATION_SERVICE_CLOUDMAGIC = "com.cloudmagic.mail";
    public static final String NOTIFICATION_SERVICE_EMAIL = "com.google.android.email";
    public static final String NOTIFICATION_SERVICE_EMAIL2 = "com.android.email";
    public static final String NOTIFICATION_SERVICE_FACEBOOK = "com.facebook.katana";
    public static final String NOTIFICATION_SERVICE_FACEBOOK_MESSAGER = "com.facebook.orca";
    public static final String NOTIFICATION_SERVICE_GMAIL = "com.google.android.gm";
    public static final String NOTIFICATION_SERVICE_HTC_EMAIL = "com.htc.android.mail";
    public static final String NOTIFICATION_SERVICE_INBOX = "com.google.android.apps.inbox";
    public static final String NOTIFICATION_SERVICE_K9 = "com.fsck.k9";
    public static final String NOTIFICATION_SERVICE_LG_EMAIL = "com.lge.email";
    public static final String NOTIFICATION_SERVICE_MAILBOX = "com.mailboxapp";
    public static final String NOTIFICATION_SERVICE_MAILDROID = "com.maildroid";
    private static final Set<String> NOTIFICATION_SERVICE_MAIL_CLIENTS;
    public static final String NOTIFICATION_SERVICE_MAIL_RU = "ru.mail.mailapp";
    public static final String NOTIFICATION_SERVICE_MICROSOFT_HEALTH = "com.microsoft.kapp";
    public static final String NOTIFICATION_SERVICE_MOTOROLA_EMAIL = "com.motorola.motoemail";
    public static final String NOTIFICATION_SERVICE_MYMAIL = "com.my.mail";
    public static final String NOTIFICATION_SERVICE_NINE = "com.ninefolders.hd3";
    public static final String NOTIFICATION_SERVICE_OUTLOOK = "com.outlook.Z7";
    public static final String NOTIFICATION_SERVICE_OUTLOOK_PREVIEW = "com.microsoft.office.outlook";
    public static final String NOTIFICATION_SERVICE_OUTLOOK_WEB = "com.microsoft.exchange.mowa";
    public static final String NOTIFICATION_SERVICE_SAMSUNG_EMAIL = "com.samsung.android.email.ui";
    public static final String NOTIFICATION_SERVICE_SOLMAIL = "net.daum.android.solmail";
    public static final String NOTIFICATION_SERVICE_TWITTER = "com.twitter.android";
    public static final String NOTIFICATION_SERVICE_YAHOO_MAIL = "com.yahoo.mobile.client.android.mail";
    public static final int STARBUCKS_BARCODE_LAYOUT_INDEX = 0;
    public static final int STARBUCK_NO_CARD_LAYOUT_INDEX = 1;
    public static final int STRAPP_LAST_UPDATED_LAYOUT = 0;
    public static final int STRAPP_MAX_ALLOWED_PAGES = 8;
    public static final int WEATHER_CLEARDAY = 0;
    public static final int WEATHER_CLEARNIGHT = 1;
    public static final int WEATHER_CLOUDY = 2;
    public static final int WEATHER_FOG = 7;
    public static final int WEATHER_RAIN = 3;
    public static final int WEATHER_RAIN_SNOW = 5;
    public static final int WEATHER_SMOKE = 8;
    public static final int WEATHER_SNOW = 6;
    public static final int WEATHER_SQUALL = 9;
    public static final int WEATHER_STRAPP_CURRENT_CONDITION = 13;
    public static final int WEATHER_STRAPP_DATE_TITLE = 11;
    public static final int WEATHER_STRAPP_DIVIDER = 12;
    public static final int WEATHER_STRAPP_HIGH_OR_CURRENT_TEMPERATURE = 22;
    public static final int WEATHER_STRAPP_LOW_TEMPERATURE = 23;
    public static final int WEATHER_STRAPP_WEATHER_ICON = 21;
    public static final int WEATHER_STRAPP_WEATHER_LAYOUT = 1;
    public static final int WEATHER_THUNDERSTORM = 4;

    public static HashMap<String, Integer> getWeatherKeys() {
        HashMap<String, Integer> keys = new HashMap<>();
        keys.put(AppEventsConstants.EVENT_PARAM_VALUE_YES, 0);
        keys.put("2", 0);
        keys.put("3", 2);
        keys.put("4", 2);
        keys.put("5", 2);
        keys.put("6", 9);
        keys.put("7", 6);
        keys.put("8", 3);
        keys.put("9", 7);
        keys.put("10", 3);
        keys.put("11", 3);
        keys.put("12", 7);
        keys.put("13", 3);
        keys.put("14", 3);
        keys.put("15", 6);
        keys.put("16", 6);
        keys.put("17", 3);
        keys.put("18", 7);
        keys.put("19", 3);
        keys.put("20", 6);
        keys.put("21", 7);
        keys.put("22", 3);
        keys.put("23", 3);
        keys.put("24", 3);
        keys.put("25", 6);
        keys.put("26", 6);
        keys.put("27", 4);
        keys.put("28", 1);
        keys.put("29", 1);
        keys.put("30", 2);
        keys.put("31", 2);
        keys.put("32", 2);
        keys.put("33", 9);
        keys.put("34", 6);
        keys.put("35", 3);
        keys.put("36", 7);
        keys.put("37", 3);
        keys.put("38", 3);
        keys.put("39", 7);
        keys.put("40", 3);
        keys.put("41", 3);
        keys.put("42", 6);
        keys.put("43", 6);
        keys.put("44", 3);
        keys.put("45", 7);
        keys.put("46", 3);
        keys.put("47", 6);
        keys.put("48", 7);
        keys.put("49", 3);
        keys.put("50", 3);
        keys.put("51", 3);
        keys.put("52", 6);
        keys.put("53", 6);
        keys.put("54", 4);
        keys.put("55", 6);
        keys.put("56", 6);
        keys.put("57", 6);
        keys.put("58", 6);
        keys.put("59", 6);
        keys.put("60", 6);
        keys.put("61", 9);
        keys.put("62", 9);
        keys.put("63", 7);
        keys.put("64", 7);
        keys.put("65", 3);
        keys.put("66", 3);
        keys.put("67", 4);
        keys.put("68", 4);
        keys.put("69", 3);
        keys.put("70", 3);
        keys.put("71", 3);
        keys.put("72", 3);
        keys.put("73", 3);
        keys.put("74", 3);
        keys.put("75", 5);
        keys.put("76", 5);
        keys.put("77", 5);
        keys.put("78", 5);
        keys.put("79", 3);
        keys.put("80", 3);
        keys.put("81", 6);
        keys.put("82", 6);
        keys.put("83", 5);
        keys.put("84", 5);
        keys.put("85", 5);
        keys.put("86", 5);
        keys.put("87", 9);
        keys.put("88", 9);
        keys.put("89", 8);
        keys.put("90", 8);
        keys.put("91", 9);
        keys.put("92", 9);
        keys.put("93", 9);
        keys.put("94", 9);
        keys.put("95", 9);
        keys.put("96", 9);
        keys.put("101", 2);
        keys.put("102", 2);
        return keys;
    }

    public static HashMap<String, String> getWeatherSimpleText() {
        HashMap<String, String> keys = new HashMap<>();
        keys.put(AppEventsConstants.EVENT_PARAM_VALUE_YES, "Clear");
        keys.put("2", "Clear");
        keys.put("3", "Cloudy");
        keys.put("4", "Cloudy");
        keys.put("5", "Cloudy");
        keys.put("6", "Dust");
        keys.put("7", "Snow");
        keys.put("8", "Drizzle");
        keys.put("9", "Fog");
        keys.put("10", "Drizzle");
        keys.put("11", "Rain");
        keys.put("12", "Haze");
        keys.put("13", "Drizzle");
        keys.put("14", "Rain");
        keys.put("15", "Snow");
        keys.put("16", "Ice");
        keys.put("17", "Drizzle");
        keys.put("18", "Fog");
        keys.put("19", "Rain");
        keys.put("20", "Snow");
        keys.put("21", "Fog");
        keys.put("22", "Rain");
        keys.put("23", "Rain");
        keys.put("24", "Sleet");
        keys.put("25", "Snow");
        keys.put("26", "Snow");
        keys.put("27", "T-Storm");
        keys.put("28", "Clear");
        keys.put("29", "Clear");
        keys.put("30", "Cloudy");
        keys.put("31", "Cloudy");
        keys.put("32", "Cloudy");
        keys.put("33", "Dust");
        keys.put("34", "Snow");
        keys.put("35", "Drizzle");
        keys.put("36", "Fog");
        keys.put("37", "Drizzle");
        keys.put("38", "Rain");
        keys.put("39", "Haze");
        keys.put("40", "Drizzle");
        keys.put("41", "Rain");
        keys.put("42", "Snow");
        keys.put("43", "Ice");
        keys.put("44", "Drizzle");
        keys.put("45", "Fog");
        keys.put("46", "Rain");
        keys.put("47", "Snow");
        keys.put("48", "Fog");
        keys.put("49", "Rain");
        keys.put("50", "Rain");
        keys.put("51", "Sleet");
        keys.put("52", "Snow");
        keys.put("53", "Snow");
        keys.put("54", "T-Storm");
        keys.put("55", "");
        keys.put("56", "");
        keys.put("57", "Snow");
        keys.put("58", "Snow");
        keys.put("59", "Snow");
        keys.put("60", "Snow");
        keys.put("61", "Dust");
        keys.put("62", "Dust");
        keys.put("63", "Fog");
        keys.put("64", "Fog");
        keys.put("65", "Hail");
        keys.put("66", "Hail");
        keys.put("67", "T-Storm");
        keys.put("68", "T-Storm");
        keys.put("69", "Drizzle");
        keys.put("70", "Drizzle");
        keys.put("71", "Rain");
        keys.put("72", "Rain");
        keys.put("73", "Hail");
        keys.put("74", "Hail");
        keys.put("75", "Rain/Snow");
        keys.put("76", "Rain/Snow");
        keys.put("77", "Rain/Snow");
        keys.put("78", "Rain/Snow");
        keys.put("79", "Rain");
        keys.put("80", "Rain");
        keys.put("81", "Snow");
        keys.put("82", "Snow");
        keys.put("83", "Rain/Snow");
        keys.put("84", "Rain/Snow");
        keys.put("85", "Rain/Snow");
        keys.put("86", "Rain/Snow");
        keys.put("87", "Dust");
        keys.put("88", "Dust");
        keys.put("89", "Smoke");
        keys.put("90", "Smoke");
        keys.put("91", "Squall");
        keys.put("92", "Squall");
        keys.put("93", "Sand");
        keys.put("94", "Sand");
        keys.put("95", "Sand");
        keys.put("96", "Sand");
        keys.put("101", "Fair");
        keys.put("102", "Fair");
        return keys;
    }

    static {
        Set<String> clients = new HashSet<>();
        clients.add(NOTIFICATION_SERVICE_AQUAMAIL);
        clients.add(NOTIFICATION_SERVICE_ASUS_EMAIL);
        clients.add(NOTIFICATION_SERVICE_BLUE_MAIL);
        clients.add(NOTIFICATION_SERVICE_BOOMERANG);
        clients.add(NOTIFICATION_SERVICE_CLOUDMAGIC);
        clients.add(NOTIFICATION_SERVICE_EMAIL);
        clients.add(NOTIFICATION_SERVICE_EMAIL2);
        clients.add(NOTIFICATION_SERVICE_GMAIL);
        clients.add(NOTIFICATION_SERVICE_HTC_EMAIL);
        clients.add(NOTIFICATION_SERVICE_INBOX);
        clients.add(NOTIFICATION_SERVICE_K9);
        clients.add(NOTIFICATION_SERVICE_LG_EMAIL);
        clients.add(NOTIFICATION_SERVICE_MAIL_RU);
        clients.add(NOTIFICATION_SERVICE_MAILBOX);
        clients.add(NOTIFICATION_SERVICE_MAILDROID);
        clients.add(NOTIFICATION_SERVICE_MOTOROLA_EMAIL);
        clients.add(NOTIFICATION_SERVICE_MYMAIL);
        clients.add(NOTIFICATION_SERVICE_NINE);
        clients.add(NOTIFICATION_SERVICE_OUTLOOK);
        clients.add(NOTIFICATION_SERVICE_OUTLOOK_WEB);
        clients.add(NOTIFICATION_SERVICE_SOLMAIL);
        clients.add(NOTIFICATION_SERVICE_YAHOO_MAIL);
        clients.add(NOTIFICATION_SERVICE_OUTLOOK_PREVIEW);
        clients.add(NOTIFICATION_SERVICE_SAMSUNG_EMAIL);
        NOTIFICATION_SERVICE_MAIL_CLIENTS = Collections.unmodifiableSet(clients);
    }

    public static boolean isMailClient(String packageName) {
        return NOTIFICATION_SERVICE_MAIL_CLIENTS.contains(packageName);
    }
}
